import type { ExerciseTags, MuscleGroup } from '../src/types/exercise'
import type { OnboardingNiveau } from '../src/types/onboarding'

const ALL_LEVELS: OnboardingNiveau[] = ['debutant', 'intermediaire', 'confirme', 'expert']
const MID_LEVELS: OnboardingNiveau[] = ['intermediaire', 'confirme', 'expert']
const ADVANCED_LEVELS: OnboardingNiveau[] = ['confirme', 'expert']

export type ExerciseDefinition = {
  id: string
  name: string
  category: MuscleGroup
  description: string
  type: 'reps' | 'duration'
  defaultReps?: number
  defaultSets?: number
  defaultDuration?: number
  equipment?: string
  muscleGroups?: MuscleGroup[]
  tags?: ExerciseTags
}

export const exerciseDefinitions: ExerciseDefinition[] = [
  // ── Gainage ──────────────────────────────────────────
  {
    id: 'plank',
    name: 'Planche',
    category: 'Gainage',
    description: 'Position de gainage sur les avant-bras, corps aligné de la tête aux talons.',
    type: 'duration',
    defaultDuration: 30,
    defaultSets: 3,
    tags: {
      objectifs: ['gainage', 'forme'],
      sports: ['running', 'velo', 'natation', 'raquettes', 'collectif'],
      zones: ['abdos'],
      materiel: ['poids-corps', 'tapis'],
      niveau: ALL_LEVELS,
    },
  },
  {
    id: 'side-plank',
    name: 'Planche latérale',
    category: 'Gainage',
    description: 'Gainage sur un avant-bras, corps de côté, hanches décollées.',
    type: 'duration',
    defaultDuration: 20,
    defaultSets: 3,
    tags: {
      objectifs: ['gainage', 'forme'],
      sports: ['running', 'velo', 'raquettes'],
      zones: ['abdos'],
      materiel: ['poids-corps', 'tapis'],
      niveau: ALL_LEVELS,
    },
  },
  {
    id: 'dead-bug',
    name: 'Dead bug',
    category: 'Gainage',
    description: 'Allongé sur le dos, bras tendus vers le plafond. Abaisser alternativement bras et jambe opposée.',
    type: 'reps',
    defaultReps: 10,
    defaultSets: 3,
    tags: {
      objectifs: ['gainage', 'mobilite', 'forme'],
      sports: ['running', 'natation'],
      zones: ['abdos'],
      materiel: ['poids-corps', 'tapis'],
      niveau: ['debutant', 'intermediaire', 'confirme'],
    },
  },
  {
    id: 'bird-dog',
    name: 'Bird dog',
    category: 'Gainage',
    description: 'À quatre pattes, tendre le bras droit et la jambe gauche simultanément, dos plat.',
    type: 'reps',
    defaultReps: 10,
    defaultSets: 3,
    tags: {
      objectifs: ['gainage', 'mobilite'],
      sports: ['running', 'rando'],
      zones: ['abdos', 'dos'],
      materiel: ['poids-corps', 'tapis'],
      niveau: ['debutant', 'intermediaire', 'confirme'],
    },
  },
  {
    id: 'crunch',
    name: 'Crunch',
    category: 'Gainage',
    description: 'Allongé sur le dos, genoux fléchis. Décoller les épaules du sol en contractant les abdominaux.',
    type: 'reps',
    defaultReps: 15,
    defaultSets: 3,
    tags: {
      objectifs: ['gainage', 'muscle'],
      sports: ['collectif'],
      zones: ['abdos'],
      materiel: ['poids-corps', 'tapis'],
      niveau: ALL_LEVELS,
    },
  },

  // ── Cuisses & Fessiers ────────────────────────────────
  {
    id: 'squat',
    name: 'Squat',
    category: 'Cuisses & Fessiers',
    description: "Pieds à largeur d'épaules, descendre jusqu'à ce que les cuisses soient parallèles au sol. Dos droit.",
    type: 'reps',
    defaultReps: 12,
    defaultSets: 4,
    tags: {
      objectifs: ['force', 'muscle', 'forme'],
      sports: ['running', 'velo', 'rando', 'collectif'],
      zones: ['jambes'],
      materiel: ['poids-corps'],
      niveau: ALL_LEVELS,
    },
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Squat bulgare',
    category: 'Cuisses & Fessiers',
    description: "Pied arrière posé sur un banc, descendre la hanche avant jusqu'au sol. Alternatif.",
    type: 'reps',
    defaultReps: 10,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'muscle'],
      sports: ['running', 'velo', 'rando'],
      zones: ['jambes'],
      materiel: ['banc', 'poids-corps'],
      niveau: MID_LEVELS,
    },
  },
  {
    id: 'lunge',
    name: 'Fente avant',
    category: 'Cuisses & Fessiers',
    description: 'Faire un grand pas en avant, descendre le genou arrière vers le sol. Alternatif.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'muscle', 'forme'],
      sports: ['running', 'rando', 'raquettes', 'collectif'],
      zones: ['jambes'],
      materiel: ['poids-corps'],
      niveau: ALL_LEVELS,
    },
  },
  {
    id: 'wall-sit',
    name: 'Wall sit',
    category: 'Cuisses & Fessiers',
    description: 'Dos contre un mur, cuisses parallèles au sol, tenir la position.',
    type: 'duration',
    defaultDuration: 40,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'forme'],
      sports: ['running', 'velo', 'rando'],
      zones: ['jambes'],
      materiel: ['poids-corps'],
      niveau: ['debutant', 'intermediaire', 'confirme'],
    },
  },

  // ── Ischio-jambiers ───────────────────────────────────
  {
    id: 'glute-bridge',
    name: 'Pont fessier',
    category: 'Ischio-jambiers',
    description: 'Allongé sur le dos, pieds à plat. Pousser les hanches vers le haut en contractant les fessiers.',
    type: 'reps',
    defaultReps: 15,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'muscle'],
      sports: ['running', 'velo'],
      zones: ['ischio', 'jambes'],
      materiel: ['poids-corps', 'tapis'],
      niveau: ALL_LEVELS,
    },
  },
  {
    id: 'hip-thrust',
    name: 'Hip thrust',
    category: 'Ischio-jambiers',
    description: 'Épaules sur un banc, pieds à plat. Pousser les hanches vers le haut avec charge ou au poids du corps.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 4,
    tags: {
      objectifs: ['force', 'muscle'],
      sports: ['velo', 'running'],
      zones: ['ischio', 'jambes'],
      materiel: ['banc', 'poids-corps'],
      niveau: MID_LEVELS,
    },
  },
  {
    id: 'rdl',
    name: 'Romanian deadlift',
    category: 'Ischio-jambiers',
    description: "Haltères devant les cuisses, descendre en gardant le dos droit jusqu'à sentir l'étirement des ischio.",
    type: 'reps',
    defaultReps: 10,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'muscle'],
      sports: ['running', 'velo', 'rando'],
      zones: ['ischio'],
      materiel: ['halteres'],
      niveau: MID_LEVELS,
    },
  },

  // ── Pectoraux ─────────────────────────────────────────
  {
    id: 'push-up',
    name: 'Pompes',
    category: 'Pectoraux',
    description: "Mains à largeur d'épaules, corps gainé. Descendre la poitrine vers le sol puis repousser.",
    type: 'reps',
    defaultReps: 12,
    defaultSets: 4,
    tags: {
      objectifs: ['force', 'muscle'],
      sports: ['collectif', 'raquettes'],
      zones: ['pecs', 'bras'],
      materiel: ['poids-corps'],
      niveau: MID_LEVELS,
    },
  },
  {
    id: 'knee-push-up',
    name: 'Pompes sur les genoux',
    category: 'Pectoraux',
    description: 'Variante des pompes en appui sur les genoux, pour diminuer la charge tout en gardant le mouvement.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'forme'],
      sports: ['collectif'],
      zones: ['pecs'],
      materiel: ['poids-corps', 'tapis'],
      niveau: ['debutant', 'intermediaire'],
    },
  },
  {
    id: 'wide-push-up',
    name: 'Pompes larges',
    category: 'Pectoraux',
    description: 'Mains plus écartées que les épaules pour cibler les pectoraux externes.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'muscle'],
      sports: ['collectif'],
      zones: ['pecs'],
      materiel: ['poids-corps'],
      niveau: ['intermediaire', 'confirme'],
    },
  },
  {
    id: 'diamond-push-up',
    name: 'Pompes diamant',
    category: 'Triceps',
    description: 'Mains rapprochées en forme de losange, ciblant les triceps et les pectoraux internes.',
    type: 'reps',
    defaultReps: 10,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'muscle'],
      sports: ['collectif'],
      zones: ['pecs', 'bras'],
      materiel: ['poids-corps'],
      niveau: ADVANCED_LEVELS,
    },
  },
  {
    id: 'dips',
    name: 'Dips sur chaise',
    category: 'Pectoraux',
    description: "Mains sur le bord d'une chaise derrière soi, fléchir les coudes et remonter.",
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'muscle'],
      sports: ['collectif'],
      zones: ['pecs', 'bras'],
      materiel: ['poids-corps', 'banc'],
      niveau: MID_LEVELS,
    },
  },

  // ── Épaules ───────────────────────────────────────────
  {
    id: 'pike-push-up',
    name: 'Pike push-up',
    category: 'Épaules',
    description: 'Hanches hautes en V renversé, fléchir les coudes pour amener la tête vers le sol.',
    type: 'reps',
    defaultReps: 10,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'muscle'],
      sports: ['natation', 'raquettes'],
      zones: ['epaules'],
      materiel: ['poids-corps'],
      niveau: ADVANCED_LEVELS,
    },
  },
  {
    id: 'lateral-raise',
    name: 'Élévations latérales',
    category: 'Épaules',
    description: "Haltères en main, lever les bras sur les côtés jusqu'à hauteur des épaules.",
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['muscle'],
      sports: ['natation', 'raquettes'],
      zones: ['epaules'],
      materiel: ['halteres'],
      niveau: MID_LEVELS,
    },
  },

  // ── Dos ───────────────────────────────────────────────
  {
    id: 'pull-up',
    name: 'Traction',
    category: 'Dos',
    description: "Barre en pronation, tirer le corps vers le haut jusqu'au menton au-dessus de la barre.",
    type: 'reps',
    defaultReps: 8,
    defaultSets: 4,
    tags: {
      objectifs: ['force', 'muscle'],
      sports: ['natation', 'raquettes'],
      zones: ['dos', 'bras'],
      materiel: ['barre'],
      niveau: ADVANCED_LEVELS,
    },
  },
  {
    id: 'row-dumbbell',
    name: 'Rowing haltère',
    category: 'Dos',
    description: "Un genou sur un banc, tirer l'haltère vers la hanche. Alternatif.",
    type: 'reps',
    defaultReps: 10,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'muscle'],
      sports: ['natation', 'velo'],
      zones: ['dos'],
      materiel: ['halteres', 'banc'],
      niveau: MID_LEVELS,
    },
  },
  {
    id: 'superman',
    name: 'Superman',
    category: 'Dos',
    description: 'Allongé face au sol, lever simultanément les bras et les jambes en contractant le bas du dos.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['gainage', 'mobilite'],
      sports: ['natation', 'running'],
      zones: ['dos'],
      materiel: ['poids-corps', 'tapis'],
      niveau: ['debutant', 'intermediaire', 'confirme'],
    },
  },

  // ── Biceps ────────────────────────────────────────────
  {
    id: 'bicep-curl',
    name: 'Curl biceps',
    category: 'Biceps',
    description: 'Haltères en supination, fléchir les coudes pour remonter les charges. Coudes fixes.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['muscle'],
      sports: ['raquettes'],
      zones: ['bras'],
      materiel: ['halteres'],
      niveau: ALL_LEVELS,
    },
  },
  {
    id: 'hammer-curl',
    name: 'Curl marteau',
    category: 'Biceps',
    description: 'Haltères en prise neutre (pouce vers le haut). Fléchir les coudes.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['muscle'],
      sports: ['raquettes', 'collectif'],
      zones: ['bras'],
      materiel: ['halteres'],
      niveau: ALL_LEVELS,
    },
  },

  // ── Triceps ───────────────────────────────────────────
  {
    id: 'tricep-extension',
    name: 'Extension triceps',
    category: 'Triceps',
    description: 'Haltère tenu à deux mains derrière la tête, étendre les bras vers le haut.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['muscle'],
      sports: ['raquettes', 'natation'],
      zones: ['bras'],
      materiel: ['halteres'],
      niveau: MID_LEVELS,
    },
  },

  // ── Mollets ───────────────────────────────────────────
  {
    id: 'calf-raise',
    name: 'Élévation mollets',
    category: 'Mollets',
    description: "Debout, monter sur la pointe des pieds lentement, descendre. Bord d'une marche pour plus d'amplitude.",
    type: 'reps',
    defaultReps: 20,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'forme'],
      sports: ['running', 'rando'],
      zones: ['mollets'],
      materiel: ['poids-corps'],
      niveau: ALL_LEVELS,
    },
  },

  // ── Cardio / Full Body ────────────────────────────────
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'Cardio / Full Body',
    description: 'Pompe au sol, remonter en saut avec les mains au-dessus de la tête. Enchaîner sans pause.',
    type: 'reps',
    defaultReps: 10,
    defaultSets: 3,
    tags: {
      objectifs: ['cardio', 'forme'],
      sports: ['running', 'collectif'],
      zones: ['jambes', 'pecs', 'abdos'],
      materiel: ['poids-corps'],
      niveau: MID_LEVELS,
    },
  },
  {
    id: 'mountain-climber',
    name: 'Mountain climber',
    category: 'Cardio / Full Body',
    description: 'En position de pompe, ramener les genoux vers la poitrine alternativement à rythme rapide.',
    type: 'duration',
    defaultDuration: 30,
    defaultSets: 3,
    tags: {
      objectifs: ['cardio', 'gainage'],
      sports: ['running', 'collectif'],
      zones: ['abdos', 'jambes'],
      materiel: ['poids-corps', 'tapis'],
      niveau: MID_LEVELS,
    },
  },
  {
    id: 'jump-squat',
    name: 'Jump squat',
    category: 'Cardio / Full Body',
    description: "Squat suivi d'un saut explosif. Atterrir doucement en fléchissant les genoux.",
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['cardio', 'force'],
      sports: ['running', 'collectif'],
      zones: ['jambes'],
      materiel: ['poids-corps'],
      niveau: ADVANCED_LEVELS,
    },
  },

  // ── Running / rando ───────────────────────────────────
  {
    id: 'step-up',
    name: 'Step-up',
    category: 'Cuisses & Fessiers',
    description: 'Monter sur un banc ou une marche en poussant sur la jambe avant. Alternatif.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'forme'],
      sports: ['running', 'rando'],
      zones: ['jambes'],
      materiel: ['banc', 'poids-corps'],
      niveau: ['debutant', 'intermediaire', 'confirme'],
    },
  },
  {
    id: 'reverse-lunge',
    name: 'Fente arrière',
    category: 'Cuisses & Fessiers',
    description: 'Reculer d\'un grand pas, descendre le genou arrière vers le sol. Moins de stress sur les genoux.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'muscle', 'forme'],
      sports: ['running', 'rando', 'raquettes'],
      zones: ['jambes'],
      materiel: ['poids-corps'],
      niveau: ALL_LEVELS,
    },
  },
  {
    id: 'single-leg-glute-bridge',
    name: 'Pont fessier unilatéral',
    category: 'Ischio-jambiers',
    description: 'Pont fessier sur une jambe, l\'autre jambe tendue. Renforce la stabilité du bassin.',
    type: 'reps',
    defaultReps: 10,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'muscle'],
      sports: ['running', 'velo'],
      zones: ['ischio', 'jambes'],
      materiel: ['poids-corps', 'tapis'],
      niveau: MID_LEVELS,
    },
  },
  {
    id: 'hip-abduction',
    name: 'Abduction de hanche',
    category: 'Cuisses & Fessiers',
    description: 'Debout ou allongé sur le côté, écarter la jambe en gardant le bassin stable.',
    type: 'reps',
    defaultReps: 15,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'forme'],
      sports: ['running', 'rando'],
      zones: ['jambes'],
      materiel: ['poids-corps', 'elastiques'],
      niveau: ALL_LEVELS,
    },
  },

  // ── Vélo / ischio ─────────────────────────────────────
  {
    id: 'nordic-curl',
    name: 'Nordic curl',
    category: 'Ischio-jambiers',
    description: 'À genoux, pieds fixés, descendre le buste vers l\'avant en contrôlant la descente avec les ischio.',
    type: 'reps',
    defaultReps: 6,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'muscle'],
      sports: ['velo', 'running'],
      zones: ['ischio'],
      materiel: ['poids-corps', 'tapis'],
      niveau: ADVANCED_LEVELS,
    },
  },

  // ── Natation / dos & épaules ──────────────────────────
  {
    id: 'band-pull-apart',
    name: 'Écartement élastique',
    category: 'Dos',
    description: 'Élastique tendu devant soi, écarter les bras sur les côtés en serrant les omoplates.',
    type: 'reps',
    defaultReps: 15,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'forme'],
      sports: ['natation', 'raquettes'],
      zones: ['dos', 'epaules'],
      materiel: ['elastiques'],
      niveau: ALL_LEVELS,
    },
  },
  {
    id: 'thoracic-rotation',
    name: 'Rotation thoracique',
    category: 'Dos',
    description: 'À quatre pattes, main derrière la tête, ouvrir le coude vers le plafond. Mobilité du haut du dos.',
    type: 'reps',
    defaultReps: 10,
    defaultSets: 3,
    tags: {
      objectifs: ['mobilite', 'forme'],
      sports: ['natation', 'raquettes'],
      zones: ['dos'],
      materiel: ['poids-corps', 'tapis'],
      niveau: ALL_LEVELS,
    },
  },
  {
    id: 'scapular-push-up',
    name: 'Pompes scapulaires',
    category: 'Dos',
    description: 'En position de pompe haute, protraction et rétraction des omoplates sans plier les coudes.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'forme'],
      sports: ['natation'],
      zones: ['dos', 'epaules'],
      materiel: ['poids-corps'],
      niveau: ['debutant', 'intermediaire', 'confirme'],
    },
  },
  {
    id: 'hollow-hold',
    name: 'Hollow hold',
    category: 'Gainage',
    description: 'Allongé sur le dos, décoller épaules et jambes du sol, bas du dos plaqué. Position de nageur.',
    type: 'duration',
    defaultDuration: 20,
    defaultSets: 3,
    tags: {
      objectifs: ['gainage', 'forme'],
      sports: ['natation'],
      zones: ['abdos'],
      materiel: ['poids-corps', 'tapis'],
      niveau: MID_LEVELS,
    },
  },

  // ── Raquettes / anti-rotation ─────────────────────────
  {
    id: 'pallof-press',
    name: 'Pallof press',
    category: 'Gainage',
    description: 'Élastique sur le côté, pousser les mains devant la poitrine en résistant à la rotation.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['gainage', 'force'],
      sports: ['raquettes', 'collectif'],
      zones: ['abdos'],
      materiel: ['elastiques'],
      niveau: MID_LEVELS,
    },
  },
  {
    id: 'external-rotation',
    name: 'Rotation externe épaule',
    category: 'Épaules',
    description: 'Coude plié à 90°, élastique fixé, tourner l\'avant-bras vers l\'extérieur. Prévention épaule.',
    type: 'reps',
    defaultReps: 15,
    defaultSets: 3,
    tags: {
      objectifs: ['forme', 'mobilite'],
      sports: ['raquettes', 'natation'],
      zones: ['epaules'],
      materiel: ['elastiques'],
      niveau: ALL_LEVELS,
    },
  },

  // ── Sport collectif ─────────────────────────────────
  {
    id: 'lateral-bound',
    name: 'Saut latéral',
    category: 'Cardio / Full Body',
    description: 'Sauter latéralement d\'un pied sur l\'autre, amortir en fléchissant. Travail d\'appuis.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['cardio', 'force'],
      sports: ['collectif', 'raquettes'],
      zones: ['jambes'],
      materiel: ['poids-corps'],
      niveau: MID_LEVELS,
    },
  },
  {
    id: 'skater-hop',
    name: 'Skater hop',
    category: 'Cardio / Full Body',
    description: 'Sauts latéraux avec amorti sur une jambe, genou légèrement fléchi. Explosivité multidirectionnelle.',
    type: 'reps',
    defaultReps: 10,
    defaultSets: 3,
    tags: {
      objectifs: ['cardio', 'force'],
      sports: ['collectif', 'raquettes'],
      zones: ['jambes'],
      materiel: ['poids-corps'],
      niveau: MID_LEVELS,
    },
  },
  {
    id: 'boxer-shuffle',
    name: 'Pas chassés',
    category: 'Cardio / Full Body',
    description: 'Déplacements rapides latéraux en chassant les pieds, genoux souples. Travail cardio et appuis.',
    type: 'duration',
    defaultDuration: 30,
    defaultSets: 3,
    tags: {
      objectifs: ['cardio', 'forme'],
      sports: ['collectif', 'raquettes'],
      zones: ['jambes'],
      materiel: ['poids-corps'],
      niveau: ALL_LEVELS,
    },
  },

  // ── Mobilité ──────────────────────────────────────────
  {
    id: 'cat-cow',
    name: 'Chat-vache',
    category: 'Gainage',
    description: 'À quatre pattes, alterner cambrure et arrondi du dos en synchronisant la respiration.',
    type: 'reps',
    defaultReps: 10,
    defaultSets: 2,
    tags: {
      objectifs: ['mobilite', 'forme'],
      sports: ['running', 'velo', 'natation', 'rando'],
      zones: ['dos', 'abdos'],
      materiel: ['poids-corps', 'tapis'],
      niveau: ALL_LEVELS,
    },
  },
  {
    id: 'hip-90-90',
    name: 'Mobilité 90/90',
    category: 'Cuisses & Fessiers',
    description: 'Assis, jambes à 90° devant et sur le côté. Basculer d\'un côté à l\'autre pour ouvrir les hanches.',
    type: 'reps',
    defaultReps: 8,
    defaultSets: 2,
    tags: {
      objectifs: ['mobilite'],
      sports: ['running', 'velo', 'rando'],
      zones: ['jambes'],
      materiel: ['poids-corps', 'tapis'],
      niveau: ALL_LEVELS,
    },
  },
  {
    id: 'worlds-greatest-stretch',
    name: 'World\'s greatest stretch',
    category: 'Cardio / Full Body',
    description: 'Fente profonde, coude au sol, rotation thoracique. Étirement dynamique full-body.',
    type: 'reps',
    defaultReps: 6,
    defaultSets: 2,
    tags: {
      objectifs: ['mobilite', 'forme'],
      sports: ['running', 'collectif', 'rando'],
      zones: ['jambes', 'dos'],
      materiel: ['poids-corps', 'tapis'],
      niveau: ALL_LEVELS,
    },
  },

  // ── Débutant ──────────────────────────────────────────
  {
    id: 'incline-push-up',
    name: 'Pompes inclinées',
    category: 'Pectoraux',
    description: 'Mains sur un banc ou une surface surélevée, corps gainé. Variante accessible des pompes.',
    type: 'reps',
    defaultReps: 12,
    defaultSets: 3,
    tags: {
      objectifs: ['force', 'forme'],
      sports: ['collectif'],
      zones: ['pecs'],
      materiel: ['banc', 'poids-corps'],
      niveau: ['debutant', 'intermediaire'],
    },
  },
]
